name: whiskers

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Whiskers
        uses: catppuccin/setup-whiskers@v2

      - name: Check JS
        run: |
          whiskers --check themes/catppuccin-latte.js templates/shapez.js.tera
          whiskers --check themes/catppuccin-frappe.js templates/shapez.js.tera
          whiskers --check themes/catppuccin-macchiato.js templates/shapez.js.tera
          whiskers --check themes/catppuccin-mocha.js templates/shapez.js.tera

      - name: Check LESS
        run: |
          whiskers --check less/latte.less templates/shapez.less.tera
          whiskers --check less/frappe.less templates/shapez.less.tera
          whiskers --check less/macchiato.less templates/shapez.less.tera
          whiskers --check less/mocha.less templates/shapez.less.tera
